server:
  port: 8764
spring:
  application:
    name: eurekaclient
  cloud:
    bus:
      trace:
        enable: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
